autoload -U promptinit && promptinit
PURE_PROMPT_SYMBOL=" "
PURE_GIT_DOWN_ARROW=""
PURE_GIT_UP_ARROW=""
prompt pure
export PATH="$HOME/.bin:$PATH"

# recommended by brew doctor
export PATH="/usr/local/bin:$PATH"
eval "$(rbenv init - --no-rehash)"

export VISUAL=nvim
export EDITOR=nvim

source ~/.config/zsh/aliases

# Completions
fpath=(~/.config/zsh/zsh-completions/src $fpath)
